#!/bin/bash

set -e

export iOSOpenDevPath="/opt/iOSOpenDev"
setupScript="$iOSOpenDevPath/bin/iod-setup-base"

if [[ -f "$setupScript" ]]; then
	echo "Running $setupScript..."
	"$setupScript"
else
	echo "Missing $setupScript"
	exit 1
fi

exit 0
