#!/bin/bash

set -e

export iOSOpenDevPath="/opt/iOSOpenDev"
sourceDir="/opt/iOSOpenDevSetup"
scriptPath="$sourceDir/bin/iod-setup"

if [[ -f "$scriptPath" ]]; then
	echo "Running $scriptPath..."
	"$scriptPath" base
	"$scriptPath" sdk -sdk iphoneos
	"$scriptPath" sdk -sdk iphonesimulator

	echo "Copying $scriptPath to $iOSOpenDevPath/bin..."
	cp -f "$scriptPath" "$iOSOpenDevPath/bin"
	rm -rf "$sourceDir"

	exit 0
else
	echo "$scriptPath not found!"

	rm -rf "$sourceDir"
	exit 1
fi
